Interext/Interext/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Interext.Models
{
    public class Event
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }

        public string ImageUrl { get; set; }

        //the options for the events or groups are only these that u are member of

        public Place Place { get; set; } // the object Place with all the info .. like previous events .. if not specified then 
        //it is the place/location of the Group

        public Group Group { get; set; } // the object Group with all the info .. like previous events .. the place/location 
        //can be overriden by the specific location of the Event

        [Required]
        public DateTime DateTimeOfTheEvent { get; set; }

        public DateTime DateTimeCreated { get; set; }
        public ICollection<UserProfile> UsersAttending { get; set; }
        public ICollection<UserProfile> UsersAwatingApproval { get; set; }
        public ICollection<UserProfile> UsersApprovedAttendance { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
        
    }
}

Interext/Interext/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Interext.Models
{
    public class EventViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Place Place { get; set; }
        public DateTime DateTimeOfTheEvent { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public ICollection<UserProfile> UsersAttending { get; set; }
        public ICollection<UserProfile> UsersInvited { get; set; }
        public ICollection<Interest> Interests { get; set; }
        public ICollection<Interest> AllInterests { get; set; }
    }
}

Interext/Interext/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Interext.Models;
using System.IO;
using Interext.OtherCalsses;

namespace Interext.Controllers
{
    public class EventController : Controller
    {
        //private InterextDB db = new InterextDB();
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: /Event/
        public ActionResult Index()
        {
            List<Event> f = db.Events.ToList();
            return View(db.Events.ToList());
        }

        // GET: /Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: /Event/Create
        public ActionResult Create()
        {
            //var model = new EventViewModel();
            //model.AllInterests = db.Interests.ToList();
            //return View(model);

            ViewBag.AllInterests = db.Interests.ToList();
            return View();
        }

        // POST: /Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,ImageUrl,DateTimeOfTheEvent")] Event @event, HttpPostedFileBase ImageUrl, string[] Interests)
        //{
        //public ActionResult Create(HttpPostedFileBase ImageUrl)
        {
            if (ModelState.IsValid)
            {
                //Event dbEvent = new Event();
                ImageSaver.SaveImage(ImageUrl, Server.MapPath("~/App_Data/uploads/events"), ImageUrl.FileName);
                //if (ImageUrl != null)
                //{
                //    if (ImageUrl.ContentLength > 0)
                //    {
                //        var fileName = Path.GetFileName(ImageUrl.FileName);
                //       // var uri = "~/App_Data/uploads/events" + @event.Id;
                //        // need to create folder for each event, the name of the folder is the id of the event
                //        var path = Path.Combine(Server.MapPath("~/App_Data/uploads/events"), fileName);
                //        ImageUrl.SaveAs(path);
                //        @event.ImageUrl = fileName;
                //    }
                //}
                @event.DateTimeCreated = DateTime.Now;
                //dbEvent.DateTimeOfTheEvent = @event.DateTimeOfTheEvent;
                //dbEvent.Description = @event.Description;
                //dbEvent.ImageUrl = @event.ImageUrl;



                @event.Interests = new List<Interest>();




                //dbEvent.Place = @event.Place;
                //dbEvent.Title = @event.Title;
                //dbEvent.UsersAttending = @event.UsersAttending;
                //dbEvent.UsersInvited = @event.UsersInvited;

                foreach (string interestID in Interests)
                {
                    int id = int.Parse(interestID);
                    Interest interest = db.Interests.SingleOrDefault(x => x.Id == id);
                    if (interest != null)
                    {
                        @event.Interests.Add(interest);
                    }
                }

                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: /Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: /Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,ImageUrl,DateTimeOfTheEvent,DateTimeCreated")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: /Event/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: /Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Interext/Interext/Controllers/InterestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Interext.Models;

namespace Interext.Controllers
{
    public class InterestController : Controller
    {
        //private InterextDB db = new InterextDB();
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: /Interest/
        public ActionResult Index()
        {
            return View(db.Interests.ToList());
        }

        // GET: /Interest/
        public ActionResult ChooseInterests(int id, string fieldName)
        {

            ViewBag.Interests = db.Interests.ToList();
            ViewBag.FieldName = fieldName;

            return View("_ChooseInterests");
        }


        // GET: /Interest/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // GET: /Interest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Interest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title")] Interest interest)
        {
            if (ModelState.IsValid)
            {
                db.Interests.Add(interest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(interest);
        }

        // GET: /Interest/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // POST: /Interest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title")] Interest interest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(interest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(interest);
        }

        // GET: /Interest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // POST: /Interest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interest interest = db.Interests.Find(id);
            db.Interests.Remove(interest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Interext/Interext/Views/Event/Create.cshtml
@model Interext.Models.EventViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Event", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUrl" id="ImageUrl" />
                @*@Html.EditorFor(model => model.ImageUrl)*@
                @Html.ValidationMessageFor(model => model.ImageUrl)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTimeOfTheEvent, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <script>
                    $(function () {
                        $("#DateTimeOfTheEvent").datepicker();
                    });
                </script>
                <input type="text" id="DateTimeOfTheEvent" name="DateTimeOfTheEvent">
                @Html.ValidationMessageFor(model => model.DateTimeOfTheEvent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Interests, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (Interext.Models.Interest item in ViewBag.AllInterests)
                {
                    <input type="checkbox" name="Interests" value="@item.Id">@Html.DisplayFor(modelItem => item.Title)<br>
                }
                @*@Html.Action("ChooseInterests", "Interest", new { id = 0, fieldName= "Interest" });*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
}

Interext/Interext/Views/Event/Delete.cshtml
@model Interext.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeOfTheEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeOfTheEvent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Interext/Interext/Views/Event/Details.cshtml
@model Interext.Models.Event

@{
    ViewBag.Title = "Details";
}

@section CssStyles{
    @Styles.Render("~/Content/eventPageCss")
}



@*<div id="single-page">*@
<div>
    <div id="content" class="right-sidebar">
        <div class="event-page-content">
            <article>
                <div class="event-intro-wrapper" style="background-image: url('/Content/images/example-images/event1.jpg');">
                    <div class="event-intro">
                        <h1 class="event-title">
                            Evening walks with dogs
                        </h1>
                        <div class="event-date">15.5</div>
                        <div class="clear"></div>
                        <div class="event-details">
                            <span class="fa fa-map-marker"></span>Tel Aviv, Israel<br />
                            <a href="~/Account/ShowProfile"><div class="createdby">Created by</div> <img src="/Content/images/example-images/profile-pic.jpg" /><div class="creator-name">Sash Pol</div></a>
                            <div class="clear"></div>
                        </div>
                        <table class="event-restrictions">
                            <tr><td colspan="2">Event for:</td></tr>
                            <tr><td>Ages</td><td> 40 - 50</td></tr>
                            <tr><td>Gender</td><td>Female</td></tr>
                            <tr><td>Interests</td><td>Dogs, Arts</td></tr>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="event-desc">
                    <p>Didn’t need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days. We’re gonna do it. On your mark get set and go now. Got a dream and we just know now we’re gonna make our dream come true. Come and dance on our floor. Take a step that is new. We’ve a loveable space that needs your face threes company too.</p>
                    <p><span id="more-372"></span></p>
                    <p>All of them had hair of gold like their mother the youngest one in curls!” It’s time to play the music. It’s time to light the lights. It’s time to meet the Muppets on the Muppet Show tonight. Straightnin’ the curves. Flatnin’ the hills Someday the mountain might get ‘em but the law never will. Today still wanted by the government they survive as soldiers of fortune. So this is the tale of our castaways they’re here for a long long time. They’ll have to make the best of things its an uphill climb.</p>
                </div>
            </article>
            <div id="ozy-share-div" class="ozy-share-div-blog">
                <span>Share This:&nbsp;</span>
                <a href="http://www.facebook.com/share.php?u=http%3A%2F%2Fcontrast.freevision.me%2Fblog%2F2013%2F11%2F27%2Fcontrast-is-your-next-level-theme%2F" title="" class="tooltip pop share-icon share-icon-facebook" style="display: inline-block;"><span class="symbol"></span></a>
                <a href="https://twitter.com/share?url=http%3A%2F%2Fcontrast.freevision.me%2Fblog%2F2013%2F11%2F27%2Fcontrast-is-your-next-level-theme%2F&amp;text=Contrast%20is%20Your%20Next%20Level%20Theme" title="" class="tooltip pop share-icon share-icon-twitter" style="display: inline-block;"><span class="symbol"></span></a>
                <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fcontrast.freevision.me%2Fblog%2F2013%2F11%2F27%2Fcontrast-is-your-next-level-theme%2F&amp;media=&amp;description=  Contrast is Your Next Level ThemeWordPress Photography Theme" title="" class="tooltip pop share-icon share-icon-pinterest" style="display: inline-block;"><span class="symbol"></span></a>
                <a href="http://www.tumblr.com/share?v=3&amp;u=http%3A%2F%2Fcontrast.freevision.me%2Fblog%2F2013%2F11%2F27%2Fcontrast-is-your-next-level-theme%2F" title="" class="tooltip pop share-icon share-icon-tumblr" style="display: inline-block;"><span class="symbol"></span></a>
                <a href="https://plusone.google.com/_/+1/confirm?hl=en&amp;url=http%3A%2F%2Fcontrast.freevision.me%2Fblog%2F2013%2F11%2F27%2Fcontrast-is-your-next-level-theme%2F" title="" class="tooltip pop share-icon share-icon-googleplus" style="display: inline-block;"><span class="symbol"></span></a>
                <a href="mailto:?subject=Contrast%20is%20Your%20Next%20Level%20Theme" title="" class="tooltip pop share-icon share-icon-email" style="display: inline-block;"><span class="symbol"></span></a>
            </div><!--#share-buttons-->
        </div>
        <div class="clear"></div>
        
    </div><!--#content-->

    <div id="sidebar" class="right-sidebar">
        <ul>
            <li>
                <form>
                    <input value="+Join" type="submit" class="join-event btn btn-special" />
                </form>
            </li>
            @*<li class="widget">
                    <h3>LOOKING FOR SOMETHING?</h3><form action="http://contrast.freevision.me/" method="get" class="wp-search-form">
                        <i class="fa fa-search"></i>
                        <input x-webkit-speech="" speech="" type="text" name="s" id="search" placeholder="Type and hit Enter">
                    </form>
                </li>*@
            <li class="widget">
                <h3>SIMILAR EVENTS</h3><div class="ozy-latest-posts">
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event1.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event2.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event3.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event4.png')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event5.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event6.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event7.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event8.jpg')"></a>
                    <a href="/Event/Details?id=1" title="Arizona Muse" style="background-image:url('/Content/images/example-images/event9.jpg')"></a>
                </div>
            </li>
        </ul>
    </div>
    <!--sidebar-->
    <div class="clear"></div>


</div>

Interext/Interext/Views/Event/Edit.cshtml
@model Interext.Models.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl)
                @Html.ValidationMessageFor(model => model.ImageUrl)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTimeOfTheEvent, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTimeOfTheEvent)
                @Html.ValidationMessageFor(model => model.DateTimeOfTheEvent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTimeCreated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTimeCreated)
                @Html.ValidationMessageFor(model => model.DateTimeCreated)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
}

Interext/Interext/Views/Event/Index.cshtml
@model IEnumerable<Interext.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTimeOfTheEvent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTimeCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Interests)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTimeOfTheEvent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTimeCreated)
        </td>
        <td>
            @if(item.Interests != null) 
            {
                foreach (var item2 in item.Interests)
                {
                    @Html.DisplayFor(modelItem => item2.Title)<br>

                }
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>